# https://docs.codecov.io/docs/codecovyml-reference

codecov:
  branch: main
  notify:
    after_n_builds: 2
comment:
  after_n_builds: 2

coverage:
  range: 80..95 # set 95% and above as solid green, everything below 80% as red
  round: nearest
  precision: 2

github_checks:
  annotations: false
