image: julia:latest

stages:
  - docs
  - pages

docs:
  stage: docs
  tags:
    - docker-any-image
  script:
    - apt-get update && apt-get install -y git
    - julia --project=docs -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'
    - julia --project=docs docs/make.jl
  artifacts:
    paths:
      - docs/build

  only:
    - julia

pages:
  stage: pages
  publish: public
  tags:
    - docker-any-image
  needs: ["docs"]
  script:
    - mkdir -p public
    - cp -r docs/build/* public/
  artifacts:
    paths:
      - public
  only:
    - julia
