# Set options for JuliaFormatter.
indent = 4
margin = 80
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = true
short_to_long_function_def = true
force_long_function_def = true
long_to_short_function_def = false
always_use_return = true
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = true
format_docstrings = false
align_assignment = false
align_struct_field = false
align_conditional = false
align_pair_arrow = false
align_matrix = false
conditional_to_if = false
normalize_line_endings = "unix"
trailing_comma = true
trailing_zero = true
join_lines_based_on_source = false
indent_submodule = false
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
for_in_replacement = "in"
variable_call_indent = []
yas_style_nesting = false
short_circuit_to_if = false
disallow_single_arg_nesting = false
overwrite = true
verbose = false
format_markdown = false
ignore = []
