# Set options for JuliaFormatter.
margin = 80
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
pipe_to_function_call = true
short_to_long_function_def = true
force_long_function_def = true
always_use_return = true
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
