# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/atmodynamics/dolaptchiev/PF/pinc/cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/atmodynamics/dolaptchiev/PF/pinc/cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/atmodynamics/dolaptchiev/PF/pinc/cmake/CMakeFiles /home/atmodynamics/dolaptchiev/PF/pinc/cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/atmodynamics/dolaptchiev/PF/pinc/cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pinc

# Build rule for target.
pinc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pinc
.PHONY : pinc

# fast build rule for target.
pinc/fast:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/build
.PHONY : pinc/fast

home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.o: home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.i: home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.s: home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.o: home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.i: home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.s: home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.o: home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.i: home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.s: home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.o: home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.i: home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.s: home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/debug.o: home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/debug.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/debug.i: home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/debug.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/debug.s: home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/debug.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/debug.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/finish.o: home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/finish.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/finish.i: home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/finish.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/finish.s: home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/finish.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/finish.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.o: home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.i: home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.s: home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/ice.o: home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/ice.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/ice.i: home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/ice.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/ice.s: home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/ice.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/ice.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/init.o: home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/init.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/init.i: home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/init.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/init.s: home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/init.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/init.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.o: home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.i: home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.s: home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.o: home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.i: home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.s: home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/output.o: home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/output.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/output.i: home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/output.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/output.s: home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/output.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/output.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.o: home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.i: home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.s: home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.o: home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.i: home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.s: home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.o: home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.i: home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.s: home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.o: home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.i: home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.s: home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/types.o: home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/types.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/types.i: home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/types.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/types.s: home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/types.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/types.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/update.o: home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/update.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/update.i: home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/update.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/update.s: home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/update.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/update.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.o: home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.i: home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.s: home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.f90.s

home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.o: home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.o

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.o

# target to build an object file
home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.o:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.o
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.o

home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.i: home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.i

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.i

# target to preprocess a source file
home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.i:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.i
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.i

home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.s: home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.s

.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.s

# target to generate assembly for a file
home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.s:
	$(MAKE) -f CMakeFiles/pinc.dir/build.make CMakeFiles/pinc.dir/home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.s
.PHONY : home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.f90.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pinc"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/algebra.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/atmosphere.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/bicgstab_tools.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/boundary.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/debug.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/debug.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/debug.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/finish.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/finish.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/finish.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/fluxes.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/ice.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/ice.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/ice.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/init.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/init.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/init.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/mpi.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/muscl.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/output.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/output.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/output.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/pinc.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/poisson.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/sizeof.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/timeScheme.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/types.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/types.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/types.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/update.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/update.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/update.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/wkb.s"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.o"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.i"
	@echo "... home/atmodynamics/dolaptchiev/PF/pinc/src/xweno.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

