"""
```julia
compute_orographic_modes!(state::State)
```

Compute the wavenumbers, intrinsic frequency and wave-action density of every orographic wave mode.

Calculates the intrinsic frequency, wavenumbers and wave-action density
of every gravity-wave mode generated by flow over topography, using linear
mountain-wave theory. The implemented formulas are as follows.

  - Intrinsic frequency:

    ```math
    \\hat{\\omega}_\\alpha = \\sigma \\left|- k_{h, \\alpha} u_h - l_{h, \\alpha} v_h\\right|
    ```

  - Horizontal wavenumbers:

    ```math
    \\begin{align*}
        k_\\alpha & = \\sigma \\mathrm{sgn} \\left(- k_{h, \\alpha} u_h - l_{h, \\alpha} v_h\\right) k_{h, \\alpha},\\\\
        l_\\alpha & = \\sigma \\mathrm{sgn} \\left(- k_{h, \\alpha} u_h - l_{h, \\alpha} v_h\\right) l_{h, \\alpha}
    \\end{align*}
    ```

  - Vertical wavenumber:

    ```math
    m_\\alpha = - \\sigma \\sqrt{\\frac{\\left(k_\\alpha^2 + l_\\alpha^2\\right) \\left(N_h^2 - \\hat{\\omega}_\\alpha^2\\right)}{\\hat{\\omega}_\\alpha^2 - f^2}}
    ```

  - Wave-action density:

    ```math
    \\mathcal{A}_\\alpha = \\frac{\\bar{\\rho}_h}{2} \\frac{\\hat{\\omega}_\\alpha \\left|\\boldsymbol{k}_\\alpha\\right|^2}{k_\\alpha^2 + l_\\alpha^2} r^2 \\left|h_{\\mathrm{w}, \\alpha}\\right|^2
    ```

Therein, ``\\bar{\\rho}_h``, ``N^2_h``, ``u_h``, and ``v_h`` are obtained by averaging between ``h_{\\mathrm{b}}`` and ``h_{\\mathrm{b}} + \\Delta h`` (using `compute_vertical_averages`), with ``\\Delta h`` provided by `compute_elevation_difference`. The reduction factor ``r`` is computed with ``compute_blocked_layer!``.

If the squared intrinsic frequency is smaller than the squared Coriolis parameter or larger than the squared buoyancy frequency (and thus outside of the gravity-wave spectrum), the vertical wavenumber and wave-action density are set to zero.

# Arguments

  - `state`: Model state.

# See also

  - [`PinCFlow.MSGWaM.BlockedLayer.compute_elevation_difference`](@ref)

  - [`PinCFlow.MSGWaM.RaySources.compute_vertical_averages`](@ref)

  - [`PinCFlow.MSGWaM.BlockedLayer.compute_blocked_layer!`](@ref)

  - [`PinCFlow.MSGWaM.RayOperations.copy_rays!`](@ref)

!!! danger "Experimental"
    The blocked-layer scheme is an experimental feature that hasn't been validated yet.
"""
function compute_orographic_modes! end

function compute_orographic_modes!(state::State)
    (; coriolis_frequency) = state.namelists.atmosphere
    (; branch, wave_modes, elastic_mode_selection) = state.namelists.wkb
    (; tref) = state.constants
    (; ko, i0, i1, j0, j1, k0) = state.domain
    (; kh, lh, hw) = state.grid
    (; spectrum) = state.wkb
    (; launch_mode_count, launch_power_fraction) =
        state.wkb.elastic_mode_selection

    if ko != 0
        return
    end

    fc = coriolis_frequency * tref

    @ivy for j in j0:j1, i in i0:i1
        deltah = compute_elevation_difference(state, i, j)

        (rhoh, n2h, uh, vh) = compute_vertical_averages(state, deltah, i, j)

        ratio = compute_blocked_layer!(state, deltah, n2h, uh, vh, i, j)

        # Set launch level.
        k = k0 - 1

        # Iterate over wave modes.
        for alpha in 1:wave_modes

            # Get the zonal and meridional wavenumbers.
            kw = kh[alpha, i, j]
            lw = lh[alpha, i, j]

            # Compute the horizontal wavenumber.
            kappa = sqrt(kw^2 + lw^2)

            # Compute intrinsic frequency from orographic wavenumbers.
            omega = -kw * uh - lw * vh

            # Adjust the signs to be consistent with the chosen frequency
            # branch.
            if omega * branch < 0
                omega *= -1
                kw *= -1
                lw *= -1
            end

            # Compute vertical wavenumber and wave-action density.
            if omega^2 > fc^2 && omega^2 < n2h

                # Compute vertical wavenumber.
                m = -branch * sqrt(kappa^2 * (n2h - omega^2) / (omega^2 - fc^2))

                # Compute wave-action density.
                a =
                    rhoh / 2 *
                    (ratio * hw[alpha, i, j])^2 *
                    omega *
                    (kappa^2 + m^2) / kappa^2

                # Set to zero if something went wrong.
                if a != a || m != m
                    a = 0
                    m = 0
                end

                # Account for critical and reflecting levels.
            else
                a = 0
                m = 0
            end

            # Save the results.
            spectrum.k[alpha, i, j, k] = kw
            spectrum.l[alpha, i, j, k] = lw
            spectrum.m[alpha, i, j, k] = m
            spectrum.omega[alpha, i, j, k] = omega
            spectrum.a[alpha, i, j, k] = a
        end

        if elastic_mode_selection
            (count, fraction) =
                apply_elastic_mode_selection!(state, spectrum.a[:, i, j, k])

            launch_mode_count[i, j] = count
            launch_power_fraction[i, j] = fraction
        end
    end

    return
end
