abstract type AbstractBackground end
abstract type AbstractCoriolis end
abstract type AbstractLimiter end
abstract type AbstractVariable end
abstract type AbstractModel end
abstract type AbstractTestCase end
abstract type AbstractBoundaries end
abstract type AbstractSponge end
abstract type AbstractMergeMode end
abstract type AbstractLaunchAlgorithm end
abstract type AbstractIntegration end
abstract type AbstractDir end
