---
config:
    theme: redux
    fontFamily: monospace
---
mindmap
    root(State)
        (Atmosphere)
        (Constants)
        (Domain)
        (Grid)
        (Namelists)
            (AtmosphereNamelist)
            (Discretization-<br>Namelist)
            (DomainNamelist)
            (GridNamelist)
            (OutputNamelist)
            (PoissonNamelist)
            (SpongeNamelist)
            (TracerNamelist)
            (WKBNamelist)
        (Poisson)
            (BicGStab)
            (Correction)
            (Operator)
            (Preconditioner)
            (Tensor)
        (Sponge)
        (Time)
        (Tracer)
            (TracerAuxiliaries)
            (TracerFluxes)
            (TracerForcings)
                (TracerWKBImpact)
            (TracerIncrements)
            (TracerPredictands)
            (Tracer-<br>Reconstructions)
        (Variables)
            (Auxiliaries)
            (Backups)
            (Fluxes)
            (Increments)
            (Predictands)
            (Reconstructions)
        (WKB)
            (MergedRays)
            (Rays)
            (SurfaceIndices)
            (WKBIncrements)
            (WKBIntegrals)
            (WKBTendencies)
