---
config:
    theme: redux
---

mindmap
    (PinCFlow.jl)
        ["Gravity-wave scheme (MSGWaM)"]
            {{Arbitrary initial state}}
            {{Coupling with resolved dynamics}}
            {{Orographic source}}
            [Approximations]
                {{1D steady-state}}
                {{1D transient}}
                {{3D transient}}
        [Parallelization]
            {{MPI base communicator for ensemble simulations}}
            {{MPI parallelization in all grid dimensions}}
        [Resolved dynamics]
            [Approximations]
                {{Boussinesq}}
                {{Compressible}}
                {{Pseudo-incompressible}}
            {{Arbitrary initial state}}
            [Backgrounds]
                {{Isentropic}}
                {{Isothermal}}
                {{Isothermal & Isentropic}}
                {{Two lapse rates}}
            {{Tracer transport}}
        [Spatial discretization]
            {{Arbitrary surface topography}}
            {{Finite-volume fluxes}}
            {{Staggered C-grid}}
            {{Vertical grid stretching}}
        [Temporal discretization]
            {{Adaptive time step}}
            {{Semi-implicit time scheme}}
