---
config:
    theme: redux
    fontFamily: monospace
---
mindmap
    root(PinCFlow)
        (Boundaries)
        (FluxCalculator)
        (Integration)
        (MPIOperations)
        (MSGWaM)
            (BoundaryRays)
            (Interpolation)
            (MeanFlowEffect)
            (RayOperations)
            (RaySources)
            (RayUpdate)
        (Output)
        (PoissonSolver)
        (Types)
            (FoundationalTypes)
            (NamelistTypes)
            (PoissonTypes)
            (TracerTypes)
            (VariableTypes)
            (WKBTypes)
        (Update)
